In [1]:
import pandas as pd
messages = pd.read_csv("SMSSpamCollection", sep='\t', names=["label","message"])

In [2]:
messages.head()

,label,message
0,ham,"Go until jurong point, crazy.. Available only ..."
1,ham,Ok lar... Joking wif u oni...
2,spam,Free entry in 2 a wkly comp to win FA Cup fina...
3,ham,U dun say so early hor... U c already then say...
4,ham,"Nah I don't think he goes to usf, he lives aro..."


Data cleaning and preprocessing

In [3]:
from nltk.corpus import stopwords 
import re
from nltk.stem import PorterStemmer
ps=PorterStemmer()


In [4]:
import nltk
nltk.download('averaged_perceptron_tagger_eng')

[nltk_data] Downloading package averaged_perceptron_tagger_eng to
[nltk_data]     C:\Users\hp\AppData\Roaming\nltk_data...
[nltk_data]   Package averaged_perceptron_tagger_eng is already up-to-
[nltk_data]       date!


True

In [5]:
corpus=[]
for i in range(0,len(messages)):
    review= re.sub("[^a-zA-Z]"," ",messages['message'][i])
    review=review.lower()
    review=review.split()
    review=[ps.stem(word) for word in review if not word in stopwords.words('english')]
    review=" ".join(review)
    corpus.append(review)

In [6]:
print(corpus[:10])

['go jurong point crazi avail bugi n great world la e buffet cine got amor wat', 'ok lar joke wif u oni', 'free entri wkli comp win fa cup final tkt st may text fa receiv entri question std txt rate c appli', 'u dun say earli hor u c alreadi say', 'nah think goe usf live around though', 'freemsg hey darl week word back like fun still tb ok xxx std chg send rcv', 'even brother like speak treat like aid patent', 'per request mell mell oru minnaminungint nurungu vettam set callertun caller press copi friend callertun', 'winner valu network custom select receivea prize reward claim call claim code kl valid hour', 'mobil month u r entitl updat latest colour mobil camera free call mobil updat co free']


create bag of words

In [7]:
from sklearn.feature_extraction.text import CountVectorizer
cv=CountVectorizer(max_features=50)

In [8]:
X=cv.fit_transform(corpus)

In [9]:
X

<5572x50 sparse matrix of type '<class 'numpy.int64'>'
	with 9896 stored elements in Compressed Sparse Row format>

In [10]:
print(X.toarray())

[[0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 ...
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 1 0]
 [0 0 0 ... 0 0 0]]


In [11]:
df = pd.DataFrame(X.toarray())

df.head()

,0,1,2,3,4,5,6,7,8,9,...,40,41,42,43,44,45,46,47,48,49
0,0,0,0,0,0,0,0,0,0,1,...,0,0,0,0,0,0,0,0,0,0
1,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
2,0,0,0,0,0,0,0,1,0,0,...,0,1,0,0,0,1,0,0,0,0
3,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
4,0,0,0,0,0,0,0,0,0,0,...,0,0,1,0,0,0,0,0,0,0


N Grams

In [12]:
cv.vocabulary_

{'go': 9,
 'got': 11,
 'ok': 27,
 'free': 7,
 'text': 41,
 'txt': 45,
 'say': 33,
 'think': 42,
 'week': 48,
 'back': 1,
 'like': 18,
 'still': 37,
 'send': 35,
 'call': 2,
 'mobil': 24,
 'home': 14,
 'want': 47,
 'today': 44,
 'day': 5,
 'repli': 32,
 'take': 39,
 'time': 43,
 'make': 22,
 'dont': 6,
 'miss': 23,
 'ur': 46,
 'da': 4,
 'lor': 19,
 'get': 8,
 'know': 16,
 'love': 20,
 'work': 49,
 'tell': 40,
 'pleas': 31,
 'see': 34,
 'pl': 30,
 'need': 25,
 'hope': 15,
 'lt': 21,
 'gt': 12,
 'ask': 0,
 'sorri': 36,
 'new': 26,
 'later': 17,
 'good': 10,
 'come': 3,
 'hi': 13,
 'stop': 38,
 'one': 28,
 'phone': 29}

BIAGRAM BIAGRAM

In [13]:
from sklearn.feature_extraction.text import CountVectorizer
cv1=CountVectorizer(max_features=100,ngram_range=(2,2))
X=cv1.fit_transform(corpus)

In [14]:
cv1.vocabulary_

{'free entri': 30,
 'claim call': 15,
 'call claim': 3,
 'free call': 29,
 'chanc win': 14,
 'txt word': 88,
 'let know': 52,
 'go home': 34,
 'pleas call': 66,
 'lt gt': 56,
 'miss call': 57,
 'want go': 97,
 'like lt': 53,
 'sorri call': 79,
 'call later': 8,
 'ur award': 89,
 'hi hi': 45,
 'call custom': 4,
 'custom servic': 22,
 'cash prize': 13,
 'po box': 67,
 'tri contact': 85,
 'draw show': 27,
 'show prize': 78,
 'prize guarante': 71,
 'guarante call': 41,
 'valid hr': 95,
 'select receiv': 75,
 'privat account': 69,
 'account statement': 0,
 'statement show': 81,
 'call identifi': 5,
 'identifi code': 48,
 'code expir': 19,
 'urgent mobil': 94,
 'call landlin': 7,
 'receiv award': 72,
 'wat time': 98,
 'ur mob': 93,
 'gud ni': 43,
 'new year': 61,
 'send stop': 77,
 'get back': 32,
 'co uk': 18,
 'gud mrng': 42,
 'nice day': 62,
 'lt decim': 55,
 'decim gt': 24,
 'txt nokia': 86,
 'good morn': 36,
 'ur friend': 91,
 'good night': 37,
 'repli call': 73,
 'last night': 51,
 'ca

BIAGRAM TRIGRAM

In [16]:
from sklearn.feature_extraction.text import CountVectorizer
cv2=CountVectorizer(max_features=100,ngram_range=(2,3))
X=cv2.fit_transform(corpus)
cv2.vocabulary_

{'free entri': 32,
 'claim call': 17,
 'call claim': 3,
 'free call': 31,
 'chanc win': 16,
 'txt word': 91,
 'let know': 54,
 'go home': 35,
 'pleas call': 70,
 'lt gt': 60,
 'miss call': 62,
 'want go': 97,
 'like lt': 55,
 'like lt gt': 56,
 'sorri call': 83,
 'call later': 11,
 'sorri call later': 84,
 'ur award': 92,
 'hi hi': 47,
 'call custom': 4,
 'custom servic': 24,
 'cash prize': 15,
 'call custom servic': 5,
 'po box': 71,
 'tri contact': 89,
 'draw show': 28,
 'show prize': 81,
 'prize guarante': 75,
 'guarante call': 42,
 'valid hr': 95,
 'draw show prize': 29,
 'show prize guarante': 82,
 'prize guarante call': 76,
 'select receiv': 78,
 'privat account': 72,
 'account statement': 0,
 'call identifi': 6,
 'identifi code': 49,
 'code expir': 21,
 'privat account statement': 73,
 'call identifi code': 7,
 'urgent mobil': 94,
 'call landlin': 10,
 'wat time': 98,
 'ur mob': 93,
 'gud ni': 44,
 'new year': 65,
 'send stop': 80,
 'get back': 34,
 'co uk': 20,
 'nice day': 66,

we apply n gram beacause i am good girl and i am not a good girl have almost same vectors but meaning is totaly opposite so , to make difference we apply n grams