In [77]:
import pandas as pd
data = pd.read_csv("kindle_reviews.csv",nrows=12000)

In [78]:
data.head()

,Unnamed: 0,asin,helpful,overall,reviewText,reviewTime,reviewerID,reviewerName,summary,unixReviewTime
0,0,B000F83SZQ,"[0, 0]",5,I enjoy vintage books and movies so I enjoyed ...,"05 5, 2014",A1F6404F1VG29J,Avidreader,Nice vintage story,1399248000
1,1,B000F83SZQ,"[2, 2]",4,This book is a reissue of an old one; the auth...,"01 6, 2014",AN0N05A9LIJEQ,critters,Different...,1388966400
2,2,B000F83SZQ,"[2, 2]",4,This was a fairly interesting read. It had ol...,"04 4, 2014",A795DMNCJILA6,dot,Oldie,1396569600
3,3,B000F83SZQ,"[1, 1]",5,I'd never read any of the Amy Brewster mysteri...,"02 19, 2014",A1FV0SX13TWVXQ,"Elaine H. Turley ""Montana Songbird""",I really liked it.,1392768000
4,4,B000F83SZQ,"[0, 1]",4,"If you like period pieces - clothing, lingo, y...","03 19, 2014",A3SPTOKDG7WBLN,Father Dowling Fan,Period Mystery,1395187200


In [79]:
data=data[['reviewText','overall']]
data.head()

,reviewText,overall
0,I enjoy vintage books and movies so I enjoyed ...,5
1,This book is a reissue of an old one; the auth...,4
2,This was a fairly interesting read. It had ol...,4
3,I'd never read any of the Amy Brewster mysteri...,5
4,"If you like period pieces - clothing, lingo, y...",4


In [80]:
data['overall'].unique()

array([5, 4, 3, 2, 1], dtype=int64)

In [81]:
data.shape

(12000, 2)

In [82]:
!pip install ydata-profiling
from ydata_profiling import ProfileReport

In [83]:
profile=ProfileReport(data,title="review analysis report",explorative=True)

In [84]:
profile.to_file("analysis_report.html")

Summarize dataset:   0%|          | 0/5 [00:00<?, ?it/s]

100%|██████████| 2/2 [00:01<00:00,  1.14it/s]


Generate report structure:   0%|          | 0/1 [00:00<?, ?it/s]

Render HTML:   0%|          | 0/1 [00:00<?, ?it/s]

Export report to file:   0%|          | 0/1 [00:00<?, ?it/s]

check null values as dataset is large so we remove null value when only few na values is there

In [85]:
data.isnull().sum()

reviewText    0
overall       0
dtype: int64

In [86]:
data['overall'].value_counts()

overall
5    5508
4    3591
3    1682
2     706
1     513
Name: count, dtype: int64

In [87]:
data['overall']=data['overall'].apply(lambda x:0 if x<4 else 1)

In [88]:
data.head()

,reviewText,overall
0,I enjoy vintage books and movies so I enjoyed ...,1
1,This book is a reissue of an old one; the auth...,1
2,This was a fairly interesting read. It had ol...,1
3,I'd never read any of the Amy Brewster mysteri...,1
4,"If you like period pieces - clothing, lingo, y...",1


In [89]:
data['reviewText']=data.reviewText.str.lower()

In [90]:
import re
import nltk
from nltk.corpus import stopwords
nltk.download('stopwords')

[nltk_data] Downloading package stopwords to
[nltk_data]     C:\Users\hp\AppData\Roaming\nltk_data...
[nltk_data]   Package stopwords is already up-to-date!


True

In [91]:
from bs4 import BeautifulSoup

In [92]:

stop_words = set(stopwords.words("english"))

def clean_text(x):
    x = re.sub(r'http\S+|www\S+', '', x)          #remove url
    x = BeautifulSoup(x,'lxml').get_text()       #remove html
    x = re.sub(r'[^a-zA-Z0-9 ]+', '', x)         #special chars
    x = " ".join([w for w in x.split() if w not in stop_words]) #stopwords
    x = " ".join(x.split())                      #extra spaces
    return x

data['reviewText'] = data['reviewText'].apply(clean_text)

C:\Users\hp\AppData\Local\Temp\ipykernel_19556\2728290414.py:5: MarkupResemblesLocatorWarning: The input looks more like a filename than markup. You may want to open this file and pass the filehandle into Beautiful Soup.
  x = BeautifulSoup(x,'lxml').get_text()       #remove html


In [93]:
data.head()

,reviewText,overall
0,enjoy vintage books movies enjoyed reading boo...,1
1,book reissue old one author born 1910 era say ...,1
2,fairly interesting read old style terminologyi...,1
3,id never read amy brewster mysteries one reall...,1
4,like period pieces clothing lingo enjoy myster...,1


In [94]:
#lemmatizer
from nltk.stem import WordNetLemmatizer
lemmatizer=WordNetLemmatizer()

In [95]:
nltk.download('wordnet')
nltk.download('omw-1.4')

[nltk_data] Downloading package wordnet to
[nltk_data]     C:\Users\hp\AppData\Roaming\nltk_data...
[nltk_data]   Package wordnet is already up-to-date!
[nltk_data] Downloading package omw-1.4 to
[nltk_data]     C:\Users\hp\AppData\Roaming\nltk_data...
[nltk_data]   Package omw-1.4 is already up-to-date!


True

In [96]:
from nltk import pos_tag

nltk.download('punkt')
nltk.download('averaged_perceptron_tagger')

[nltk_data] Downloading package punkt to
[nltk_data]     C:\Users\hp\AppData\Roaming\nltk_data...
[nltk_data]   Package punkt is already up-to-date!
[nltk_data] Downloading package averaged_perceptron_tagger to
[nltk_data]     C:\Users\hp\AppData\Roaming\nltk_data...
[nltk_data]   Package averaged_perceptron_tagger is already up-to-
[nltk_data]       date!


True

In [97]:
def lemmatizeword(text):
    return " ".join([lemmatizer.lemmatize(word,'v') for word in text.split()])

In [98]:
data['reviewText']=data['reviewText'].apply(lambda x: lemmatizeword(x))

In [99]:
data.head()

,reviewText,overall
0,enjoy vintage book movies enjoy read book plot...,1
1,book reissue old one author bear 1910 era say ...,1
2,fairly interest read old style terminologyi gl...,1
3,id never read amy brewster mysteries one reall...,1
4,like period piece clothe lingo enjoy mystery a...,1


In [100]:
#train test split
from sklearn.model_selection import train_test_split
X_train,X_test, y_train,y_test=train_test_split(data['reviewText'],data['overall'],test_size=0.20)

Bag of words

In [101]:
from sklearn.feature_extraction.text import CountVectorizer
bow=CountVectorizer()
X_train_bow=bow.fit_transform(X_train).toarray()
X_test_bow= bow.transform(X_test).toarray()

TFIDF

In [102]:
from sklearn.feature_extraction.text import TfidfVectorizer
Tfidf=TfidfVectorizer()
X_train_Tfidf=Tfidf.fit_transform(X_train).toarray()
X_test_Tfidf= Tfidf.transform(X_test).toarray()

In [103]:
from sklearn.naive_bayes import GaussianNB
gb=GaussianNB()
nbmodel_bow=gb.fit(X_train_bow,y_train)
nbmodel_tfidf=gb.fit(X_train_Tfidf,y_train)

In [104]:
from sklearn.metrics import accuracy_score, confusion_matrix

In [105]:
y_pred_bow=nbmodel_bow.predict(X_test_bow)
y_pred_tfidf=nbmodel_tfidf.predict(X_test_Tfidf)

In [106]:
acc_bow=accuracy_score(y_test,y_pred_bow)
acc_tfidf=accuracy_score(y_test,y_pred_tfidf)

In [107]:
print(acc_bow)
print(acc_tfidf)

0.5908333333333333
0.56


In [108]:
confusion_matrix(y_test,y_pred_bow)

array([[ 326,  278],
       [ 704, 1092]], dtype=int64)

In [109]:
confusion_matrix(y_test,y_pred_tfidf)

array([[351, 253],
       [803, 993]], dtype=int64)

Word2veb

In [110]:
import gensim
import gensim.downloader as api
wv= api.load("word2vec-google-news-300")

In [111]:
import numpy as np

def get_vector(text):

    words=text.split()

    valid_words=[word for word in words if word in wv]

    if len(valid_words)==0:
        return np.zeros(300)

    vectors=[wv[word] for word in valid_words]

    return np.mean(vectors,axis=0)

In [112]:
X_train_vec = np.vstack(X_train.apply(get_vector))

X_test_vec = np.vstack(X_test.apply(get_vector))

In [113]:
model=GaussianNB()
model.fit(X_train_vec,y_train)

GaussianNB()

In [114]:
from sklearn.linear_model import LogisticRegression

model1=LogisticRegression()

model1.fit(X_train_vec,y_train)

LogisticRegression()

In [115]:
pred=model.predict(X_test_vec)

In [116]:
pred1=model1.predict(X_test_vec)

In [117]:
print(accuracy_score(y_test,pred1))
print(accuracy_score(y_test,pred))

0.8029166666666666
0.6383333333333333


80% accuracy (applied word2veb for word embeddings and for model training used logistic regression)
63 percent accuracy (used Gaussian naive baise)